#ifndef SFMLDEMO_ACTIONTYPES_H
#define SFMLDEMO_ACTIONTYPES_H

enum action_types
{
    CHARACTER_MOVE_UP,
    CHARACTER_STOP_UP,
    CHARACTER_MOVE_DOWN,
    CHARACTER_STOP_DOWN,
    CHARACTER_MOVE_RIGHT,
    CHARACTER_STOP_RIGHT,
    CHARACTER_MOVE_LEFT,
    CHARACTER_STOP_LEFT,
    MOUSE_BUTTON_PRESSED,
    MOUSE_BUTTON_RELEASED
};

#endif //SFMLDEMO_ACTIONTYPES_H
